use std::{collections::{BTreeMap, HashMap}, sync::{Arc, RwLock}};
use std::hash::{Hash, Hasher};
use std::fmt::Debug;
use crate::{fixture::{selection::{DummySelection, Selection, StrictSelection}, Fixture, FixtureRef}, parameter::parameter_value::ParameterValue};

/// A blending mode, assigned to each layer, defines how multiple layers changing the same parameter are resolved
#[derive(Debug, Clone)]
pub enum BlendingMode {
    /// Add this value to the current one
    Add,
    /// This layer takes precedence over the previous ones if it has a higher value.
    Highest,
    /// This layer takes precedence over the previous ones if it was updated recently.
    Latest,
    /// Multiply the current value with this one. This operation takes priority over all previous ones.
    Multiply,
    /// Override any previous value. This operation takes priority over all previous ones.
    Override,
    /// Multiply the current value with this one. This operation takes priority over previous multiplications
    /// and overrides.
    MultiplyOverride
}

#[derive(Clone)]
pub(super) struct FixtureParameterPair {
    pub fixture: FixtureRef,
    pub parameter: usize,
}

impl PartialEq for FixtureParameterPair {
    fn eq(&self, other: &Self) -> bool {
        self.fixture.uuid() == other.fixture.uuid() && self.parameter == other.parameter
    }
}

impl Eq for FixtureParameterPair {}

impl Hash for FixtureParameterPair {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.fixture.uuid().hash(state);
        self.parameter.hash(state);
    }
}

impl Debug for FixtureParameterPair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "FixtureParameterPair {{ fixture_uuid: {}, parameter: {} }}", self.fixture.uuid(), self.parameter)
    }
}

/// A layer contains a set of parameter modifications ([FixtureParameterPair]) that are applied to fixtures.
/// 
/// Each layer has a different "priority" or "blending mode" that defines its order.
/// This allows us to have different priorities on code that modifies parameters, and allows control of overrides.
/// 
/// Each layer is only associated to one "playback", which may be a scene, an effect, the program or anything else.
#[derive(Debug)]
pub struct Layer {
    pub name: String,
    pub blending_mode: BlendingMode,
    /// The numerical priority of the layer. Higher numbers override lower numbers.
    /// Blending mode takes precedence over priority.
    pub priority: u32,
    /// Whether this layer is actually applied to the fixtures
    pub active: bool,
    /// A list of parameters set by the fixture. This is updated by any code that modifies a parameter.
    /// Values here are kept between frames, and will need to be manually removed when no longer active.
    /// Order does not matter.
    pub(super) parameters: HashMap<FixtureParameterPair, ParameterValue>,
    /// The generated selection of fixtures
    /// 
    /// This selection is not set explicitly, but is generated by the set of parameters used
    selection: DummySelection,
}

impl Layer {
    pub fn new(name: &str, blending_mode: BlendingMode, priority: u32) -> Layer {
        Layer {
            name: name.to_string(),
            blending_mode,
            priority,
            active: true,
            selection: DummySelection {  },
            parameters: HashMap::new(),
        }
    }

    /// Set the value of a parameter for a fixture
    pub fn set_value(&mut self, fixture: FixtureRef, parameter: usize, value: ParameterValue) {
        let pair = FixtureParameterPair {
            fixture: fixture.clone(),
            parameter,
        };

        self.parameters.insert(pair, value);
    }

    /// Remove all values and parameters for a fixture
    /// 
    /// Call this function when there is a change in the set of parameters or fixtures affected by this layer
    pub fn clear_values(&mut self) {
        self.parameters.clear();
    }
}

