use std::cmp::max;
use std::collections::{BTreeMap, HashMap};
use std::fmt::Debug;
use std::hash::{Hash, Hasher};
use std::ops::{Add, Mul};
use std::sync::{Arc, RwLock};
use std::time::Instant;

use log::debug;
use uuid::Uuid;

use crate::fixtures::selection::{DummySelection, Selection, StrictSelection};
use crate::fixtures::{Fixture, FixtureRef, ParameterUpdate};
use crate::parameters::parameter_value::ParameterValue;
use crate::parameters::ParameterDescription;
use crate::utils::WithUuid;

/// A blending mode, assigned to each layer, defines how multiple layers changing the same parameter are resolved
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlendingMode {
    /// Add this value to the current one
    Add,
    /// This layer takes precedence over the previous ones if it has a higher value.
    Highest,
    /// This layer takes precedence over the previous ones if it was updated recently.
    Latest,
    /// Multiply the current value with this one. This operation takes priority over all previous ones.
    Multiply,
    /// Override any previous value. This operation takes priority over all previous ones.
    Override,
    /// Multiply the current value with this one. This operation takes priority over previous multiplications
    /// and overrides.
    MultiplyOverride,
}

impl Default for BlendingMode {
    fn default() -> Self {
        BlendingMode::Add
    }
}

#[derive(Clone, Hash, PartialEq, Eq)]
pub(super) struct FixtureParameterPair {
    pub fixture: FixtureRef,
    pub parameter: usize,
}

impl Debug for FixtureParameterPair {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "FixtureParameterPair {{ fixture_uuid: {}, parameter: {} }}",
            self.fixture.uuid(),
            self.parameter
        )
    }
}

/// A layer contains a set of parameter modifications ([FixtureParameterPair]) that are applied to fixtures.
///
/// Each layer has a different "priority" or "blending mode" that defines its order.
/// This allows us to have different priorities on code that modifies parameters, and allows control of overrides.
///
/// Each layer is only associated to one "playback", which may be a scene, an effect, the program or anything else.
#[derive(Debug)]
pub struct Layer {
    pub name: String,
    pub uuid: Uuid,
    pub blending_mode: BlendingMode,
    /// The numerical priority of the layer. Higher numbers override lower numbers.
    /// Blending mode takes precedence over priority.
    pub priority: u32,
    /// Whether this layer is actually applied to the fixtures
    pub active: bool,
    /// A list of parameters set by the fixture. This is updated by any code that modifies a parameter.
    /// Values here are kept between frames, and will need to be manually removed when no longer active.
    /// Order does not matter.
    pub(super) parameters: HashMap<FixtureParameterPair, ParameterValue>,
    /// The generated selection of fixtures
    ///
    /// This selection is not set explicitly, but is generated by the set of parameters used
    selection: DummySelection,
}

impl Layer {
    pub fn new(name: &str, blending_mode: BlendingMode, priority: u32) -> Layer {
        Layer {
            name: name.to_string(),
            uuid: Uuid::new_v4(),
            blending_mode,
            priority,
            active: true,
            selection: DummySelection {},
            parameters: HashMap::new(),
        }
    }

    /// Set the value of a parameter for a fixture
    pub fn set_value(&mut self, fixture: FixtureRef, parameter: usize, value: ParameterValue) {
        let pair = FixtureParameterPair {
            fixture: fixture.clone(),
            parameter,
        };

        self.parameters.insert(pair, value);
    }

    /// Remove all values and parameters for a fixture
    ///
    /// Call this function when there is a change in the set of parameters or fixtures affected by this layer
    pub fn clear_values(&mut self) {
        self.parameters.clear();
    }
}

impl WithUuid for Layer {
    fn uuid(&self) -> Uuid {
        self.uuid
    }
}

/// Given an array of parameter updates from different layers, returns the resulting value
fn make_decision(values: &Vec<ParameterUpdate>) -> Option<ParameterValue> {
    use BlendingMode::*;

    if values.is_empty() {
        return None;
    } else if values.len() == 1 {
        return Some(values[0].value.clone());
    }

    fn cmp_modes(lhs: &BlendingMode, rhs: &BlendingMode) -> std::cmp::Ordering {
        use std::cmp::Ordering::*;

        use BlendingMode::*;

        #[inline(always)]
        fn to_int_order(bm: &BlendingMode) -> u8 {
            use BlendingMode::*;

            match bm {
                Override => 0,
                Latest => 1,
                Highest => 2,
                Add => 3,
                Multiply => 4,
                MultiplyOverride => 5,
            }
        }

        to_int_order(lhs).cmp(&to_int_order(rhs))
    }

    #[derive(Debug, Clone)]
    struct ResolvedUpdate {
        pub value: ParameterValue,
        pub blending_mode: BlendingMode,
        pub priority: u32,
        pub updated: Instant,
    }

    impl std::ops::Add for ResolvedUpdate {
        type Output = ResolvedUpdate;

        fn add(self, rhs: Self) -> Self::Output {
            ResolvedUpdate {
                value: (self.value + rhs.value.clone()).unwrap_or(rhs.value),
                blending_mode: rhs.blending_mode,
                priority: max(self.priority, rhs.priority),
                updated: max(self.updated, rhs.updated),
            }
        }
    }

    impl std::ops::Mul for ResolvedUpdate {
        type Output = ResolvedUpdate;

        fn mul(self, rhs: Self) -> Self::Output {
            ResolvedUpdate {
                value: (self.value * rhs.value.clone()).unwrap_or(rhs.value),
                blending_mode: rhs.blending_mode,
                priority: max(self.priority, rhs.priority),
                updated: max(self.updated, rhs.updated),
            }
        }
    }

    let values = values
        .iter()
        .filter_map(|update| {
            let (blending_mode, priority, active) = update
                .layer
                .read(|l| (l.blending_mode, l.priority, l.active))
                .unwrap_or_default();

            if active {
                Some(ResolvedUpdate {
                    value: update.value.clone(),
                    blending_mode,
                    priority,
                    updated: update.updated,
                })
            } else {
                None
            }
        })
        .collect::<Vec<_>>();

    let mut working_value: Option<ResolvedUpdate> = None;

    // Pass 1: Add
    values
        .iter()
        .filter(|up| up.blending_mode == BlendingMode::Add)
        .for_each(|up| {
            if let Some(v) = &working_value {
                working_value = Some(v.clone() + up.clone());
            } else {
                working_value = Some(up.clone());
            }
        });

    // Pass 2: Replace
    for update in values.iter() {
        let last_blending_mode = working_value.as_ref().map_or(Add, |v| v.blending_mode);

        if cmp_modes(&update.blending_mode, &last_blending_mode) == std::cmp::Ordering::Greater {
            continue;
        }

        match (&working_value, update.blending_mode) {
            (None, _) => {
                working_value = Some(update.clone());
            }
            (Some(last), Highest) => {
                if let Some(cmp) = last.value.partial_cmp(&update.value) {
                    if cmp == std::cmp::Ordering::Less {
                        working_value = Some(update.clone());
                    } else if cmp == std::cmp::Ordering::Equal && update.priority > last.priority {
                        working_value = Some(update.clone());
                    }
                }
            }
            (Some(last), Latest) => {
                if update.updated > last.updated {
                    working_value = Some(update.clone());
                } else if update.updated == last.updated && update.priority > last.priority {
                    working_value = Some(update.clone());
                }
            }
            (Some(last), Override) => {
                if last.blending_mode != Override || update.priority > last.priority {
                    working_value = Some(update.clone());
                }
            }
            (Some(_), _) => {}
        }
    }

    // Pass 3: Multiply
    for update in values
        .iter()
        .filter(|up| up.blending_mode == Multiply || up.blending_mode == MultiplyOverride)
    {
        if let Some(last) = working_value.as_ref() {
            if update.blending_mode == MultiplyOverride || last.blending_mode != Override {
                working_value = Some(last.clone() * update.clone());
            }
        } else {
            working_value = Some(update.clone());
        }
    }

    working_value.map(|v| v.value)
}

#[cfg(test)]
mod tests {
    use BlendingMode::*;
    use ParameterValue::*;

    use super::*;
    use crate::setup_logger;
    use crate::utils::SmartRef;

    fn quick_parameter_with_time(
        value: ParameterValue,
        blending_mode: BlendingMode,
        priority: u32,
        delay: u32,
    ) -> ParameterUpdate {
        let layer = Layer::new("Test", blending_mode, priority);

        // ParameterUpdate {
        //     parameter_index: 0,
        //     value,
        //     layer: FakeLayer { blending_mode, priority },
        //     time: Instant::now() + std::time::Duration::from_secs(delay as u64),
        // }
        ParameterUpdate {
            value,
            layer: SmartRef::new_from_move(layer),
            updated: Instant::now() + std::time::Duration::from_secs(delay as u64),
        }
    }

    fn quick_parameter(value: ParameterValue, blending_mode: BlendingMode, priority: u32) -> ParameterUpdate {
        quick_parameter_with_time(value, blending_mode, priority, 0)
    }

    #[test]
    fn parameter_add() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![1.0]), Add, 0),
            quick_parameter(Number(vec![3.0]), Add, 0),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![4.0])));
    }

    #[test]
    fn parameter_add_and_multiply() {
        let layer1 = Layer::new("Test", BlendingMode::Add, 0);
        let layer2 = Layer::new("Test", BlendingMode::Multiply, 0);

        let value = make_decision(&vec![
            quick_parameter(Number(vec![0.5]), Add, 0),
            quick_parameter(Number(vec![3.48]), Multiply, 0),
            quick_parameter(Number(vec![1.0]), Add, 0),
            quick_parameter(Number(vec![2.0]), Multiply, 0),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![10.44])));
    }

    #[test]
    fn parameter_highest() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![1.5]), Highest, 0),
            quick_parameter(Number(vec![3.48]), Highest, 0),
            quick_parameter(Number(vec![2.0]), Add, 0),
            quick_parameter(Number(vec![3.0]), Multiply, 0),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![10.44])));
    }

    #[test]
    fn parameter_highest_but_lower() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![1.5]), Highest, 0),
            quick_parameter(Number(vec![3.48]), Highest, 0),
            quick_parameter(Number(vec![9.0]), Add, 0),
            quick_parameter(Number(vec![3.0]), Multiply, 0),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![27.0])));
    }

    #[test]
    fn parameter_latest() {
        let value = make_decision(&vec![
            quick_parameter_with_time(Number(vec![5.0]), Latest, 0, 0),
            quick_parameter_with_time(Number(vec![6.0]), Add, 0, 1),
            quick_parameter_with_time(Number(vec![12.0]), Highest, 0, 1),
            quick_parameter_with_time(Number(vec![7.0]), Latest, 0, 2),
            quick_parameter_with_time(Number(vec![3.0]), Multiply, 0, 3),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![21.0])));
    }

    #[test]
    fn parameter_latest_but_older() {
        let value = make_decision(&vec![
            quick_parameter_with_time(Number(vec![5.0]), Latest, 0, 0),
            quick_parameter_with_time(Number(vec![6.0]), Add, 0, 1),
            quick_parameter_with_time(Number(vec![12.0]), Highest, 0, 3),
            quick_parameter_with_time(Number(vec![7.0]), Latest, 0, 2),
            quick_parameter_with_time(Number(vec![3.0]), Multiply, 0, 3),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![36.0])));
    }

    #[test]
    fn parameter_override() {
        let value = make_decision(&vec![
            quick_parameter_with_time(Number(vec![5.0]), Latest, 0, 0),
            quick_parameter_with_time(Number(vec![6.0]), Add, 0, 1),
            quick_parameter_with_time(Number(vec![12.0]), Highest, 0, 3),
            quick_parameter_with_time(Number(vec![7.0]), Latest, 0, 2),
            quick_parameter_with_time(Number(vec![3.0]), Multiply, 0, 3),
            quick_parameter_with_time(Number(vec![1.45]), Override, 0, 0),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![1.45])));
    }

    #[test]
    fn parameter_override_different_priorities() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![5.0]), Latest, 0),
            quick_parameter(Number(vec![1.0]), Override, 0),
            quick_parameter(Number(vec![2.0]), Override, 2),
            quick_parameter(Number(vec![3.0]), Override, 1),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![2.0])));
    }

    #[test]
    fn parameter_override_multiply() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![5.0]), Latest, 0),
            quick_parameter(Number(vec![2.0]), Multiply, 0),
            quick_parameter(Number(vec![3.0]), MultiplyOverride, 0),
            quick_parameter(Number(vec![3.5]), MultiplyOverride, 0),
            quick_parameter(Number(vec![1.0]), Override, 0),
            quick_parameter(Number(vec![2.0]), Override, 2),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![21.0])));
    }

    #[test]
    fn parameter_highest_vector() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![4.0, 3.0]), Highest, 0),
            quick_parameter(Number(vec![1.0, 5.0]), Highest, 0),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![1.0, 5.0])));
    }

    #[test]
    fn parameter_highest_vector_equal_squares() {
        let value = make_decision(&vec![
            quick_parameter(Number(vec![4.0, 3.0, 3.0]), Highest, 0),
            quick_parameter(Number(vec![3.0, 4.0, 3.0]), Highest, 2),
            quick_parameter(Number(vec![3.0, 3.0, 4.0]), Highest, 1),
        ]);

        assert_eq!(value, Some(ParameterValue::Number(vec![3.0, 4.0, 3.0])));
    }

    #[test]
    fn no_parameters() {
        let value = make_decision(&vec![]);

        assert_eq!(value, None);
    }

    #[test]
    fn single_parameter() {
        let value = make_decision(&vec![quick_parameter(Number(vec![1.0]), Add, 0)]);

        assert_eq!(value, Some(ParameterValue::Number(vec![1.0])));
    }

    #[test]
    fn single_parameter_multiply() {
        let value = make_decision(&vec![quick_parameter(Number(vec![3.0]), Multiply, 0)]);

        assert_eq!(value, Some(ParameterValue::Number(vec![3.0])));
    }
}
